devices:
  # Lights
  - name: "Pendant Light"
    room: "Living Room"
    ip: "192.168.5.40"
    model: "KL130B"
    driver: "kasa"

  - name: "Pendant Light"
    room: "Landing"
    ip: "192.168.5.41"
    model: "KL130B"
    driver: "kasa"

  - name: "Pendant Light"
    room: "Snug"
    ip: "192.168.5.42"
    model: "KL130B"
    driver: "kasa"

  - name: "Pendant Light"
    room: "Box Room"
    ip: "192.168.5.43"
    model: "KL130B"
    driver: "kasa"

  - name: "Pendant Light"
    room: "Hallway"
    ip: "192.168.5.44"
    model: "KL110B"
    driver: "kasa"

  - name: "Pendant Light"
    room: "Front Bedroom"
    ip: "192.168.5.45"
    model: "KL50B"
    driver: "kasa"

  - name: "Bookshelf Light Strip"
    room: "Office"
    ip: "192.168.5.51"
    model: "L900"
    driver: "tapo"

  - name: "Christmas Lights"
    room: "Living Room"
    ip: "192.168.5.48"
    model: "HS100"
    driver: "kasa"

  - name: "Up-Lighter"
    room: "Living Room"
    ip: "192.168.5.49"
    model: "HS100"
    driver: "kasa"

  - name: "Lava Lamp"
    room: "Back Bedroom"
    ip: "192.168.5.50"
    model: "HS100"
    driver: "kasa"

  - name: "Pendant Light"
    room: "Back Bedroom"
    ip: "192.168.3.70"
    # model: "L535B"
    model: "KL110B"
    driver: "tapo"

  - name: "Pendant Light"
    room: "Office"
    ip: "192.168.3.71"
    # model: "L535B"
    model: "KL110B"
    driver: "tapo"

  # Other things
  - name: "Work Desk Power"
    room: "Office"
    ip: "192.168.5.70"
    model: "HS110"
    driver: "kasa"

  - name: "Radiator Power"
    ip: "192.168.5.73"
    model: "P100"
    driver: "tapo"

  - name: "Air Purifier"
    ip: "192.168.5.72"
    model: "HS110"
    driver: "kasa"

  - name: "Kettle"
    room: "Kitchen"
    ip: "192.168.5.74"
    model: "HS110"
    driver: "kasa"

  - name: "Slow Cooker"
    room: "Kitchen"
    ip: "192.168.5.75"
    model: "P100"
    driver: "tapo"

  - name: "PC Desk Power"
    room: "Den"
    ip: "192.168.5.71"
    model: "HS110"
    driver: "kasa"

  - name: "Toaster"
    room: "Kitchen"
    ip: "192.168.5.77"
    model: "P110"
    driver: "tapo"

  - name: "Bookcase Ball Lights"
    room: "Office"
    ip: "192.168.5.52"
    model: "P110"
    driver: "tapo"

  - name: "Microwave"
    room: "Kitchen"
    ip: "192.168.5.76"
    model: "KP115"
    driver: "kasa"

  - name: "AV Power"
    room: "Living Room"
    ip: "192.168.5.78"
    model: "KP115"
    driver: "kasa"
