devices:
  # Lights
  - name: "Pendant Light"
    room: "Living Room"
    ip: "192.168.3.50"
    model: "KL130B"
    driver: "kasa"

  - name: "Pendant Light"
    room: "Landing"
    ip: "192.168.3.51"
    model: "KL130B"
    driver: "kasa"

  - name: "Pendant Light"
    room: "Snug"
    ip: "192.168.3.52"
    model: "KL130B"
    driver: "kasa"

  - name: "Pendant Light"
    room: "Box Room"
    ip: "192.168.3.53"
    model: "KL130B"
    driver: "kasa"

  - name: "Pendant Light"
    room: "Hallway"
    ip: "192.168.3.54"
    model: "KL110B"
    driver: "kasa"

  - name: "Pendant Light"
    room: "Front Bedroom"
    ip: "192.168.3.55"
    model: "KL50B"
    driver: "kasa"

  - name: "Bookshelf Light Strip"
    room: "Office"
    ip: "192.168.3.56"
    model: "L900"
    driver: "tapo"

  - name: "Christmas Lights"
    room: "Living Room"
    ip: "192.168.3.57"
    model: "HS100"
    driver: "kasa"

  - name: "Up-Lighter"
    room: "Living Room"
    ip: "192.168.3.58"
    model: "HS100"
    driver: "kasa"

  - name: "Lava Lamp"
    room: "Back Bedroom"
    ip: "192.168.3.59"
    model: "HS100"
    driver: "kasa"

  # - name: "Pendant Light"
  #   room: "Back Bedroom"
  #   ip: "192.168.3.70"
  #   # model: "L535B"
  #   model: "KL110B"
  #   driver: "tapo"

  # - name: "Pendant Light"
  #   room: "Office"
  #   ip: "192.168.3.71"
  #   # model: "L535B"
  #   model: "KL110B"
  #   driver: "tapo"

  # Other things
  - name: "Work Desk Power"
    room: "Office"
    ip: "192.168.3.60"
    model: "HS110"
    driver: "kasa"

  - name: "Radiator Power"
    ip: "192.168.3.61"
    model: "P100"
    driver: "tapo"

  - name: "Air Purifier"
    ip: "192.168.3.62"
    model: "HS110"
    driver: "kasa"

  - name: "Kettle"
    room: "Kitchen"
    ip: "192.168.3.63"
    model: "HS110"
    driver: "kasa"

  - name: "Slow Cooker"
    room: "Kitchen"
    ip: "192.168.3.64"
    model: "P100"
    driver: "tapo"

  - name: "PC Desk Power"
    room: "Den"
    ip: "192.168.3.65"
    model: "HS110"
    driver: "kasa"

  - name: "Toaster"
    room: "Kitchen"
    ip: "192.168.3.67"
    model: "P110"
    driver: "tapo"

  - name: "Bookcase Ball Lights"
    room: "Office"
    ip: "192.168.3.68"
    model: "P110"
    driver: "tapo"

  - name: "Microwave"
    room: "Kitchen"
    ip: "192.168.3.69"
    model: "KP115"
    driver: "kasa"
