devices:
  # Lights
  - name: "Pendant Light"
    room: "Living Room"
    ip: "192.168.1.50"
    model: "KL130B"
    driver: "kasa"

  - name: "Pendant Light"
    room: "Den"
    ip: "192.168.1.51"
    model: "KL130B"
    driver: "kasa"

  - name: "Pendant Light"
    room: "Kitchen"
    ip: "192.168.1.52"
    model: "KL130B"
    driver: "kasa"

  - name: "Pendant Light"
    room: "Bedroom"
    ip: "192.168.1.53"
    model: "KL130B"
    driver: "kasa"

  - name: "Pendant Light"
    room: "Hallway"
    ip: "192.168.1.54"
    model: "KL110B"
    driver: "kasa"

  - name: "Pendant Light"
    room: "Office"
    ip: "192.168.1.55"
    model: "KL50B"
    driver: "kasa"

  - name: "Monitors Backlight Strip"
    room: "Office"
    ip: "192.168.1.56"
    model: "L900"
    driver: "tapo"

  - name: "Christmas Lights"
    room: "Living Room"
    ip: "192.168.1.57"
    model: "HS100"
    driver: "kasa"

  - name: "Up-Lighter"
    room: "Living Room"
    ip: "192.168.1.58"
    model: "HS100"
    driver: "kasa"

  - name: "Lava Lamp"
    room: "Bedroom"
    ip: "192.168.1.59"
    model: "HS100"
    driver: "kasa"

  # Other things
  - name: "Work Desk Power"
    room: "Office"
    ip: "192.168.1.60"
    model: "HS110"
    driver: "kasa"

  - name: "Radiator Power"
    ip: "192.168.1.61"
    model: "HS110"
    driver: "kasa"

  - name: "Air Purifier"
    ip: "192.168.1.62"
    model: "HS110"
    driver: "kasa"

  - name: "Kettle"
    room: "Kitchen"
    ip: "192.168.1.63"
    model: "HS110"
    driver: "kasa"

  - name: "Slow Cooker"
    room: "Kitchen"
    ip: "192.168.1.64"
    model: "P100"
    driver: "tapo"

  - name: "PC Desk Power"
    room: "Den"
    ip: "192.168.1.65"
    model: "HS110"
    driver: "kasa"

  - name: "TV Power"
    room: "Living Room"
    ip: "192.168.1.66"
    model: "HS110"
    driver: "kasa"

  - name: "Fridge Freezer"
    room: "Kitchen"
    ip: "192.168.1.67"
    model: "P110"
    driver: "tapo"

  - name: "Washing Machine"
    room: "Kitchen"
    ip: "192.168.1.68"
    model: "P110"
    driver: "tapo"

  - name: "Microwave"
    room: "Kitchen"
    ip: "192.168.1.69"
    model: "KP115"
    driver: "kasa"
