name: Publish master to DockerHub

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set Parameters
        id: params
        run: |
          echo "::set-output name=date::$(date +%Y-%m-%d-%H-%M)"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          file: ./build/package/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64/v8
          tags: "alexswilliams/homepower:${{ github.ref_name }}--${{ steps.params.outputs.date }}--${{ github.sha }}"


      - name: Build and push
        run: make docker